# vim: foldmethod=marker

# Basic {{{1
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin= 'make -f make_cygwin.mak'
    mac = 'make -f make_mac.mak'
    unix = 'make -f make_unix.mak'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tyru/eskk.vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'

# depends: gist-vim
[[plugins]]
repo = 'mattn/webapi-vim'

# depends: previm
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'thinca/vim-zenspace'
# 1}}}

# 検索関連 {{{1
[[plugins]]
repo = 'osyo-manga/vim-anzu'
# 1}}}

# Color {{{1
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sjl/badwolf'
# 1}}}

# EditorConfig {{{1
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
# 1}}}

# Git {{{1
[[plugins]]
repo = 'tpope/vim-fugitive'
# 1}}}

# GitHub {{{1
[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'
# 1}}}

# Wakatime {{{1
[[plugins]]
repo = 'wakatime/vim-wakatime'
# 1}}}
