# vim: foldmethod=marker

# Basic {{{1
[[plugins]]
if = '''has('nvim')'''
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1
# 起動時にdeopleteを有効にする
hook_source = 'let g:deoplete#enable_at_startup = 1'
# deoplete.nvim用の設定をロード
hook_post_source = 'source ~/.vim/rc/plugins/deoplete.rc.vim'

[[plugins]]
if = '''has('vim')'''
repo = 'Shougo/neocomplete'
depends = 'context_filetype.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['context_filetype.vim', 'neosnippet-snippets']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

[[plugins]]
repo = 'janko-m/vim-test'
on_cmd = [':TestNearest', ':TestFile', ':TestSuite', ':TestLast', ':TestVisit']
depends = 'neoterm'

# 1}}}

# CoffeeScript {{{1
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'
# 1}}}

# GitHub {{{1
[[plugins]]
repo = 'mattn/gist-vim'
depends = 'webapi-vim'
on_cmd = 'Gist'
# 1}}}

# Golang {{{1
[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
if = '''has('nvim')'''
repo = 'zchee/deoplete-go'
depends = 'deoplete.nvim'
build = 'make'
on_ft = 'go'
# 1}}}

# HTML / CSS {{{1
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'sass', 'scss', 'jsx']

[[plugins]]
repo = 'wavded/vim-stylus'
on_ft = 'stylus'
# 1}}}

# Jade {{{1
[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = 'jade'
# 1}}}

# JavaScript {{{1
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'
hook_source='source ~/.vim/rc/plugins/vim-javascript.rc.vim'

# es6のハイライト
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'
depends = 'vim-javascript'

# stage-0 のsyntax highlight
[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = 'javascript'
depends = 'yajs.vim'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = 'javascript'
hook_source='''
" よりカラフルなハイライト
let g:vim_jsx_pretty_colorful_config = 1
'''

[[plugins]]
repo  = 'heavenshell/vim-jsdoc'
on_ft = 'javascript'

[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = 'javascript'
hook_source = 'source ~/.vim/rc/plugins/vim-flow.rc.vim'
# 1}}}

# Markdown {{{1
[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = 'markdown'


[[plugins]]
repo = 'rcmdnk/vim-markdown'
depends = ['vim-gfm-syntax', 'vim-markdown-quote-syntax']
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
depends = 'open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_ft = 'markdown'
# 1}}}

# Text {{{1
[[plugins]]
repo = 'ujihisa/neco-look'
on_i = 1
# 1}}}

# Terraform {{{1
[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
# 1}}}

# Python {{{1
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python', 'python3']

[[plugins]]
if = '''has('nvim')'''
repo = 'zchee/deoplete-jedi',
depends = ['jedi-vim', 'deoplete.nvim']
on_ft = ['python', 'python3']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python', 'python3']
on_i = 1

[[plugins]]
repo = 'alfredodeza/pytest.vim'
on_ft = ['python', 'python3']
# 1}}}

# Vim Script{{{1
[[plugins]]
repo = 'ynkdir/vim-vimlparser'
on_ft = 'vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = 'vim'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = 'vim-vimlparser'
on_ft = 'vim'

[[plugins]]
repo = 'rhysd/try-colorscheme.vim'
on_cmd = 'TryColorscheme'
# 1}}}
