# vim: foldmethod=marker

# Basic {{{1
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler'
depends = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
depends = 'unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'rhysd/clever-f.vim'

[[plugins]]
if = '''! has('kaoriya')'''
repo = 'deton/jasentence.vim'

# depends: gist-vim
[[plugins]]
repo = 'mattn/webapi-vim'

# depends: previm
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'thinca/vim-zenspace'

[[plugins]]
repo = 'kana/vim-submode'

# depends vim-go
[[plugins]]
if = '''has('nvim')'''
repo = 'kassio/neoterm'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# 1}}}

# 検索関連 {{{1
[[plugins]]
repo = 'osyo-manga/vim-anzu'
# 1}}}

# Color {{{1
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = '29decibel/codeschool-vim-theme'

[[plugins]]
repo = 'nyomaszto/crayon'

[[plugins]]
repo = 'aereal/vim-colors-japanesque'
# 1}}}

# EditorConfig {{{1
[[plugins]]
repo = 'editorconfig/editorconfig-vim'
# 1}}}

# Git {{{1
[[plugins]]
repo = 'tpope/vim-fugitive'
# 1}}}

# GitHub {{{1
[[plugins]]
repo = 'rhysd/github-complete.vim'

[[plugins]]
repo = 'junegunn/vim-emoji'
# 1}}}

# Wakatime {{{1
[[plugins]]
repo = 'wakatime/vim-wakatime'
# 1}}}
